name: acct-test
on: 
  pull_request_target:
    types: [labeled]

jobs:
  pr-acc-test:
    if: ${{github.repository == 'huaweicloud/terraform-provider-huaweicloud' && 
            contains(github.event.pull_request.labels.*.name, 'saft to test') }}
    runs-on: ubuntu-latest
    env:
      HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
      HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
      HW_REGION_NAME: "cn-north-4"
      HW_ENTERPRISE_PROJECT_ID: "0"
    steps:
      - run:  echo "${{github.event.pull_request.head.repo.full_name}}"
          
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.16"

      - name: fetch pull request head
        run: |
           /usr/bin/git remote add upstream ${{github.server_url}}/${{github.event.pull_request.head.repo.full_name}}
           /usr/bin/git fetch upstream ${{github.head_ref}}

      - run: scripts/pr_acctest_basic.sh ${{github.base_ref}} upstream/${{github.head_ref}} >pr-acc-test.log

      - id: get-comment-body
        run: |
          body="$(cat pr-acc-test.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          reactions: "rocket"
